apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthmed-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthmed-api
  template:
    metadata:
      labels:
        app: healthmed-api
    spec:
      containers:
        - name: healthmed-api
          image: devflavio/healthmed-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver,1433;Database=BdHealthMed;User ID=sa;Password=NovaSenhaForte123;Trusted_Connection=False;TrustServerCertificate=True;"
