name: Build and Deploy to DOKS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: devflavio/healthmed-api
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build e Publish
      run: |
        dotnet restore HealthMed.API.sln
        dotnet publish HealthMed.API/HealthMed.Access.API.csproj -c Release -o ./publish

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build da imagem Docker
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .

    - name: Push da imagem para Docker Hub
      run: |
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Autenticar doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Configurar kubeconfig
      run: doctl kubernetes cluster kubeconfig save healthmedkubernets

    - name: Restart do deployment no cluster
      run: kubectl rollout restart deployment healthmed-api
